services:
  server:
    platform: linux/amd64
    image: softvence/${PACKAGE_NAME}:latest
    container_name: ${PACKAGE_NAME}_api
    profiles:
      - prod
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/${PACKAGE_NAME}_db
      BASE_URL: ${BASE_URL}
      PORT: 5052
      ENABLE_CRON: false
    ports:
      - '5052:5052'
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        echo '🏁 Waiting for DB...';
        sleep 5;
        npx prisma migrate deploy;
        echo '🚀 Starting app...';
        pnpm start
      "
    volumes:
      - files-data:/app/uploads
      - temp-data:/app/tmp
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://0.0.0.0:5052/api/health']
      interval: 30s
      timeout: 10s
      retries: 5

  cron:
    platform: linux/amd64
    image: softvence/${PACKAGE_NAME}:latest
    container_name: ${PACKAGE_NAME}_cron
    profiles:
      - prod
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/${PACKAGE_NAME}_db
      BASE_URL: http://0.0.0.0:5052/api
      PORT: 5053
      ENABLE_CRON: true
    depends_on:
      db:
        condition: service_healthy
      server:
        condition: service_healthy
    command: >
      sh -c "
        echo '⏰ Starting cron worker...';
        pnpm start
      "
    volumes:
      - files-data:/app/uploads
      - temp-data:/app/tmp

  db:
    image: postgres:17
    container_name: ${PACKAGE_NAME}_db
    restart: always
    profiles:
      - dev
      - prod
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${PACKAGE_NAME}_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy
    container_name: jupiterm_caddy
    restart: always
    profiles:
      - prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "caddy validate --config /etc/caddy/Caddyfile"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  db_data:
  files-data:
  temp-data:
  caddy_data:
  caddy_config:

networks:
  default:
    name: ${PACKAGE_NAME}_network
    labels:
      - 'project=${PACKAGE_NAME}'
