-- CreateEnum
DO $$ BEGIN
    CREATE TYPE "SchemaType" AS ENUM ('ARTICLE', 'BLOG_POSTING', 'FAQ_PAGE', 'HOW_TO', 'LOCAL_BUSINESS', 'ORGANIZATION');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- AlterEnum (Safe enum expansion)
ALTER TYPE "PostStatus" ADD VALUE IF NOT EXISTS 'IN_REVIEW';
ALTER TYPE "PostStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "PostStatus" ADD VALUE IF NOT EXISTS 'SCHEDULED';
ALTER TYPE "PostStatus" ADD VALUE IF NOT EXISTS 'UPDATING';

-- AlterTable (Additive optional columns)
ALTER TABLE "blog"
ADD COLUMN IF NOT EXISTS "seoTitle" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "metaDescription" TEXT,
ADD COLUMN IF NOT EXISTS "focusKeyword" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "secondaryKeywords" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "slug" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "canonicalUrl" VARCHAR(500),
ADD COLUMN IF NOT EXISTS "robotsIndex" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "robotsFollow" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "ogTitle" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "ogDescription" TEXT,
ADD COLUMN IF NOT EXISTS "ogImageUrl" VARCHAR(500),
ADD COLUMN IF NOT EXISTS "twitterTitle" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "twitterDescription" TEXT,
ADD COLUMN IF NOT EXISTS "twitterImageUrl" VARCHAR(500),
ADD COLUMN IF NOT EXISTS "authorName" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "authorBio" TEXT,
ADD COLUMN IF NOT EXISTS "publishedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "featuredImageAlt" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "featuredImageCaption" TEXT,
ADD COLUMN IF NOT EXISTS "isPillarPage" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "parentClusterId" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "seriesName" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "seriesOrder" INTEGER,
ADD COLUMN IF NOT EXISTS "previousArticleId" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "nextArticleId" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "schemaType" "SchemaType" NOT NULL DEFAULT 'ARTICLE',
ADD COLUMN IF NOT EXISTS "faqSection" JSONB;
